### PR TITLE
FAQ Items/Rules/rules_to_duels.html

### PR DESCRIPTION
**Pull request by Karbn**
for Rules to Duels/Wagers

### CODE REVIEW

**Comment by Novaras** [comment]
Not merging until you do the rewording and reformatting we discussed in query.

**Review by suomy — CHANGES_REQUESTED** [review]
Compare to [existing](https://github.com/TB-FAQ/TB-FAQ/blob/master/FAQ%20Items/Rules/duel_rules_and_guide.html).

Wording is occasionally awkward.
- Line 27: "Rules to Duels" is awkward in English. Consider "Duel Rules", "Rules for Dueling" (which you use later), or even "Rules to Dueling".
- Line 35: Why use quotes here? Use a more active phrasing, if possible. Instead of "A duel refers to", say "A duel is", for example.
- Line 43: "Original agreement" isn't a proper noun, so this sentence should probably start as "The original agreement".
- Line 43: Using repetition for emphasis should generally be avoided, it's not generally considered particularly professional. Use a single bold "Always" to accomplish this point, perhaps?
- Line 49: Second sentence feels flaky. Compare to present version on `master` for alternatives?
- Line 68: "Glad you asked!" does not contribute to understanding, and is questionably professional. Perhaps remove entirely?

Strongly recommend comparing to the existing version and refining this.

**Comment by Karbn** [comment]
Did compare to previous version, in fact 90% of this is C/P from the original text. Will fix up when I have the time

Sent from my iPad

On Nov 23, 2017, at 5:52 AM, suomy <notifications@github.com<mailto:notifications@github.com>> wrote:


@suomy requested changes on this pull request.

Compare to existing<https://github.com/TB-FAQ/TB-FAQ/blob/master/FAQ%20Items/Rules/duel_rules_and_guide.html>.

Wording is occasionally awkward.

  *   Line 27: "Rules to Duels" is awkward in English. Consider "Duel Rules", "Rules for Dueling" (which you use later), or even "Rules to Dueling".
  *   Line 35: Why use quotes here? Use a more active phrasing, if possible. Instead of "A duel refers to", say "A duel is", for example.
  *   Line 43: "Original agreement" isn't a proper noun, so this sentence should probably start as "The original agreement".
  *   Line 43: Using repetition for emphasis should generally be avoided, it's not generally considered particularly professional. Use a single bold "Always" to accomplish this point, perhaps?
  *   Line 49: Second sentence feels flaky. Compare to present version on master for alternatives?
  *   Line 68: "Glad you asked!" does not contribute to understanding, and is questionably professional. Perhaps remove entirely?

Strongly recommend comparing to the existing version and refining this.

**Comment by suomy** [comment]
The previous version you're working with is not the same as the current version in master, please take a closer look.

**Comment by suomy** [comment]
Looks like this is currently inactive. Please feel free to reopen if you do any more work on this branch.

**Pull request closed without merging**
